// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {updater} from '../models';
import {systeminfo} from '../models';

export function CheckForUpdate(arg1:string):Promise<backend.UpdateCheckResponse>;

export function DownloadUpdate(arg1:updater.UpdateInfo):Promise<updater.InstallResult>;

export function GetConfigSummary():Promise<backend.ConfigSummary>;

export function GetLanguage():Promise<string>;

export function GetSystemInfo():Promise<systeminfo.Info>;

export function GetWindowTitle():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Run():Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function WriteTestLog():Promise<backend.LogWriteResult>;
