// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate(arg1) {
  return window['go']['backend']['App']['CheckForUpdate'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['backend']['App']['DownloadUpdate'](arg1);
}

export function GetConfigSummary() {
  return window['go']['backend']['App']['GetConfigSummary']();
}

export function GetLanguage() {
  return window['go']['backend']['App']['GetLanguage']();
}

export function GetSystemInfo() {
  return window['go']['backend']['App']['GetSystemInfo']();
}

export function GetWindowTitle() {
  return window['go']['backend']['App']['GetWindowTitle']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function Run() {
  return window['go']['backend']['App']['Run']();
}

export function SetLanguage(arg1) {
  return window['go']['backend']['App']['SetLanguage'](arg1);
}

export function WriteTestLog() {
  return window['go']['backend']['App']['WriteTestLog']();
}
